package io.jyberion.mmorpg.common.message;

public enum MessageType {
    LOGIN_REQUEST,
    LOGIN_RESPONSE,
    CHANNEL_REGISTRATION,
    GET_AVAILABLE_CHANNELS,
    AVAILABLE_CHANNELS_RESPONSE,
    CHANNEL_HEARTBEAT,
    CHANNEL_AUTHENTICATION,
    CHANNEL_AUTHENTICATION_RESPONSE,
    CHAT,
    PLAYER_ACTION,
    RPC_CALL; 
}
